[package]
name = "frostmark"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
description = "HTML/Markdown renderer for libcosmic"

[dependencies]
libcosmic.workspace = true
html5ever = "0.38"
markup5ever_rcdom = "0.38.0"
bitflags = "2.11.0"

comrak = { version = "0.50", default-features = false, optional = true }

[dev-dependencies]
tokio.workspace = true
open = "5.3.3"
reqwest = "0.13.2"

[features]
default = ["markdown", "libcosmic-wgpu", "libcosmic-tokio", "libcosmic-windowing"]
markdown = ["dep:comrak"]
libcosmic-wgpu = ["libcosmic/wgpu"]
libcosmic-tokio = ["libcosmic/tokio"]
libcosmic-windowing = ["libcosmic/x11", "libcosmic/wayland"]
